# -*- coding: utf-8 -*-
"""Text generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ygnAA51rpk9wetrpEERG738w6u4UmbnX
"""

import torch
!pip install transformers torch
from transformers import pipeline
generator =pipeline(
    "text-generation",
    model="gpt2"
)
prompt="Artificial intelligence in finance will"
result=generator(prompt,max_length=50,num_return_sequences=1)
print("AI generated text:")
print(result[0]["generated_text"])